### ISSUE TITLE
Fork or branch?

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [JaimeCalzadaVIMS/geomesh#37]
Hi Jaime (@jreniel @JaimeCalzadaVIMS),

I don't know your Geomesh development plan. So, I was wondering if you prefer that I continue contributing to your repo and merge all my development into a "dev/noaa" branch instead of "main" or do you prefer if I work on the fork in ocs-modeling?

I have some changes in different branches that I don't like to diverge too much, so I'd prefer a branch where I can combine my changes more frequently.

**Comment by jreniel** [comment]
My preference is that you create your own copy, with a new package name, where you develop at your own will. I plan to continue development of Geomesh, but since it is difficult to coordinate with NOAA, and I am making several changes to some of your contributions, it would be best if you simply continue your work on the ocs repo under a different name, and disconnected from my repo. It's perfectly OK that the two repos diverge, NOAA has their own version, and I have mine, where I can pursue the goals I have set for this project. Would that be an acceptable solution for moving forward?
Thanks.

**Comment by jreniel** [comment]
Just to be clear, what I am saying is that you can _continue_ working with the code as it is right now, you don't need to start over again. Simply rename all the imports to something other than geomesh (to avoid name collisions in the packages), and do a hard push to the ocs repo, using a new package name.

**Comment by SorooshMani-NOAA** [comment]
Sure, that works. Can I go ahead and remove my current dev branches from your repo as well?

**Comment by jreniel** [comment]
Yes you can. But please also make sure to preserve the commit history. Don't delete the .git and create a new one,  simply change the URL of the remote and any references to the name geomesh in the code, and commit that, and that would be your "starting point". I am also preserving your commit history on my side, so your contribution history will continue to be available in the future.
All they had to do was ask to use the code, there was no need to try to force me out of it. Thanks.

**Comment by SorooshMani-NOAA** [comment]
I think there's a miscommunication, I personally will be happy to continue collaborating on the same repo. My question was merely pointing out the existing few diverging dev branches I had, and I was wondering if I could create a dev/noaa branch where I merge all my branches into more frequently and then you can accept a pull from dev/noaa to main whenever you have time to review them.

With that being said, if you still prefer that I continue on the fork instead of main repo, I'll make sure I'll preserve the commit history and thank you for doing the same.

**Comment by jreniel** [comment]
Details aside, to me it's fair game to create a diverging fork if you:
1) Ask the code owner for permission to do so.
2) Change the name of the package
and
3) Preserve the commit history.

If you think you can meet these three points, which I believe are standard operating procedures when doing a diverging hard fork, then by all means you can do the diverging hard fork and continue developing from there. That's all I am asking for, which I think it's fair. Thanks.

**Comment by SorooshMani-NOAA** [comment]
OK, thanks.

**Comment by SorooshMani-NOAA** [comment]
Jaime (@jreniel, @JaimeCalzadaVIMS), I was informed that a separate parallel discussion is going on between you and NOAA CSDL leadership about Geomesh development, repo and fork. I was not aware of that discussion. I don't have any say in this matter. The decision is up to the result of the other discussion.

**Comment by jreniel** [comment]
Is NOAA interested in the name of the package, or the contents of the package?

**Comment by jreniel** [comment]
Is NOAA interested in the name of the package, or the contents of the package? You are free to fork it under a different name, or even if you insist on using the same name, that's fine as well, just do a hard fork on the OCS repo (aka disconnect your  ocs copy from mine).

**Comment by jreniel** [comment]
For the record, I can't forcefully gift this work to you if you don't delete the repo from the noaa-ocs-modeling namespace first. I guess that's part of the battery of technical knowledge that is lacking.
